In [1]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("../cnn/MNIST_data/", one_hot=True)

Extracting ../cnn/MNIST_data/train-images-idx3-ubyte.gz
Extracting ../cnn/MNIST_data/train-labels-idx1-ubyte.gz
Extracting ../cnn/MNIST_data/t10k-images-idx3-ubyte.gz
Extracting ../cnn/MNIST_data/t10k-labels-idx1-ubyte.gz


In [2]:
batch_data = mnist.train.next_batch(batch_size=10)

In [3]:
class SimpleCnn(object):
    pass

In [4]:
sess = tf.Session(config=tf.ConfigProto(device_count={'cpu':0}))

## 前向传播

In [5]:
X = tf.placeholder(dtype=tf.float32, shape=[None, 784])
y = tf.placeholder(dtype=tf.float32, shape=[None, 10])

In [6]:
new_X = tf.reshape(X, shape=(-1, 28, 28, 1))

In [7]:
filter_num = 2
filter_size = [2, 2]
conv_layer_1 = tf.layers.conv2d(new_X, filter_num, filter_size, activation=tf.nn.relu)

In [8]:
pool_size = [3, 3]
strides = [1, 1]
pool_layer_1 = tf.layers.max_pooling2d(conv_layer_1, pool_size, strides)
pool_layer_1.shape

TensorShape([Dimension(None), Dimension(25), Dimension(25), Dimension(2)])

In [9]:
dense_layer_1 = tf.layers.flatten(pool_layer_1)
dense_layer_1.shape

TensorShape([Dimension(None), Dimension(1250)])

In [10]:
dense_layer_2 = tf.layers.dense(dense_layer_1, 300, activation=tf.nn.relu)
dense_layer_2.shape

TensorShape([Dimension(None), Dimension(300)])

In [11]:
dense_layer_3 = tf.layers.dense(dense_layer_2, 10)
dense_layer_3.shape

TensorShape([Dimension(None), Dimension(10)])

In [12]:
init = tf.global_variables_initializer()
sess.run(init)

In [13]:
result = sess.run(dense_layer_3, feed_dict={X: batch_data[0]})
result[0: 2]

array([[ 0.03848676, -0.05132953,  0.07005227,  0.0010495 , -0.02480341,
        -0.0331322 , -0.04311711, -0.03262414,  0.05422526, -0.00223096],
       [ 0.03419515, -0.06222498,  0.01751604, -0.0051253 , -0.04862711,
        -0.03931988, -0.06902321, -0.01610937,  0.04811184, -0.01437413]], dtype=float32)

## Loss 

In [14]:
print(dense_layer_3.get_shape)
print(y.get_shape)

<bound method Tensor.get_shape of <tf.Tensor 'dense_1/BiasAdd:0' shape=(?, 10) dtype=float32>>
<bound method Tensor.get_shape of <tf.Tensor 'Placeholder_1:0' shape=(?, 10) dtype=float32>>


In [15]:
loss = tf.losses.softmax_cross_entropy(y, dense_layer_3)

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.



In [16]:
 sess.run(loss, feed_dict={X: batch_data[0], y: batch_data[1]})

2.3154128

In [20]:
self_loss = -  y * tf.log(tf.nn.softmax(dense_layer_3))

In [21]:
 sess.run(self_loss, feed_dict={X: batch_data[0], y: batch_data[1]})[0:2]

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  2.30330729],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  2.30218434]], dtype=float32)

In [22]:
loss_sum = tf.reduce_mean(tf.reduce_sum(self_loss, axis=1))
sess.run(loss_sum, feed_dict={X: batch_data[0], y: batch_data[1]})

2.3154128

##  Train

In [23]:
optimozer = tf.train.GradientDescentOptimizer(learning_rate=0.5)

In [24]:
trainer = optimozer.minimize(loss)

In [28]:
for i in range(100):
    sess.run(trainer, feed_dict={X: batch_data[0], y: batch_data[1]})
    if (i % 10 == 0)
        print(sess.run(loss, feed_dict={X: batch_data[0], y: batch_data[1]}))

SyntaxError: invalid syntax (<ipython-input-28-438209fe6ee3>, line 3)

In [124]:
predict = tf.argmax(dense_layer_3, axis=1)
print(sess.run(predict, feed_dict={X: batch_data[0], y: batch_data[1]}))
print(sess.run(tf.argmax(y, axis=1), feed_dict={X: batch_data[0], y: batch_data[1]}))

[3 6 7 0 4 3 0 1 0 5]
[3 6 7 0 4 3 0 1 0 5]


In [36]:
test_data = tf.constant([[[[1], [2], [3]], [[4], [5], [6]], [[3], [2], [1]]]], dtype=tf.float32)
test_data.get_shape

<bound method Tensor.get_shape of <tf.Tensor 'Const_12:0' shape=(1, 3, 3, 1) dtype=float32>>

In [ ]:
# [filter_height, filter_width, in_channels, out_channels]
# [2, 2, 1, 2]
kernel_initializer = tf.Variable()

In [37]:
layer_1 = tf.layers.conv2d(test_data, 2, [2, 2], activation=tf.nn.relu)

In [38]:
init = tf.global_variables_initializer()
sess.run(init)

In [39]:
sess.run(layer_1)

array([[[[ 0.        ,  1.1882062 ],
         [ 0.        ,  2.10733032]],

        [[ 0.        ,  3.87725353],
         [ 0.        ,  4.60345984]]]], dtype=float32)

In [ ]:
layer_1 = tf.layers.conv2d(test_data, 2, [2, 2], activation=tf.nn.relu)